export enum ROUTES {
  HOME = "/",
  BLOGS = "/blogs",
  CATEGORIES = "/categories",
  TRASH_BLOGS = "/trash/blogs",
  TRASH_CATEGORIES = "/trash/categories",
  LOGIN = "/login",
  REGISTER = "/register",
  FORGOT_PASSWORD = "/forgot-password",
  PROFILE = "/profile",
  PREVIEW_BLOG = "/blogs/preview",
  NOTIFICATIONS = "/notifications",
  CONTACTS = "/contacts",
  REPLIES = "/replies",
}
