export enum TITLES {
  HOME = "Trang chủ",
  BLOGS = "Quản lý bài viết",
  CATEGORIES = "Quản lý danh mục bài viết",
  TRASH_BLOGS = "Quản lý bài viết đã xoá",
  TRASH_CATEGORIES = "Quản lý danh mục bài viết đã xoá",
  LOGIN = "Đăng nhập",
  REGISTER = "Đăng ký tài khoản",
  FORGOT_PASSWORD = "Quên mật khẩu",
  PROFILE = "Thông tin tài khoản",
  CREATE_CATEGORY = "Thêm danh mục bài viết",
  UPDATE_CATEGORY = "Sửa danh mục bài viết",
  CREATE_BLOG = "Thêm bài viết",
  UPDATE_BLOG = "Sửa bài viết",
  PREVIEW_BLOG = "Xem trước bài viết",
  SCROLL_TO_TOP = "Lên đầu trang",
  RESTORE_RECORD = "Phục hồi bản ghi",
  RESTORE_RECORDS = "Phục hồi nhiều bản ghi",
  DELETE_RECORDS = "Xoá vĩnh viễn nhiều bản ghi",
  DELETE_RECORD = "Xoá vĩnh viễn bản ghi",
  NEW_RECORD = "Thêm mới bản ghi",
  PREVIEW_RECORD = "Xem bản ghi",
  SOFT_DELETE_RECORD = "Xoá bản ghi",
  EDIT_RECORD = "Sửa bản ghi",
  VIEW_NOTIFICATIONS = "Xem tất cả thông báo",
  CONTACTS = "Quản lý liên hệ",
}
